Repository cri-o/cri-o.io, pull requests merged in 2019-04, with the labels that each got.

#28 index: s/Clear/kata!
  index.md
Labels: lgtm, needs-ok-to-test, size/XS

#30 Fix kubelet typo in index.md
  index.md
Labels: dco-signoff: yes, lgtm, needs-ok-to-test, size/XS

#31 Update kubeadm 'Try Now' field
  index.md
Labels: dco-signoff: yes, size/XS

#32 Add OWNERS file
  OWNERS
Labels: dco-signoff: yes, lgtm, size/XS

#33 Add CNCF project logo to main page
  _includes/cncf.html
  _layouts/default.html
  assets/css/style.scss
  logo/cncf-logo.png
Labels: approved, dco-signoff: yes, lgtm, size/S
